image: node:10.15.3

stages:
  - test
  - deploy

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

test:
  type: test
  script:
    - npm install
    - npm install newman
    - npm run start
    - npm run test

deploy:
  type: deploy
  tags:
    - docker
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_IMAGE:staging
    - docker tag $CONTAINER_IMAGE:staging registry.heroku.com/mobapp-api/web
    - docker push registry.heroku.com/mobapp-api/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app mobapp-api
  only:
    - master
