image: docker:18.09.7

stages:
  - test
  - deploy

services:
  - postgres:12.2-alpine
  - docker:18.09.7-dind

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

test:
  type: test
  image: maxtermax/mob
  script:
    - npm install
    - npm run start

deploy:
  type: deploy
  tags:
    - docker
  script:
    - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
    - export BUILD_ID=$(($RANDOM))
    - docker pull $CONTAINER_IMAGE:latest
    - docker tag $CONTAINER_IMAGE:$BUILD_ID registry.heroku.com/mobapp-api/web
    - docker push registry.heroku.com/mobapp-api/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app mobapp-api
  only:
    - master
