version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mobexample@db:5432/postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mobexample
      POSTGRES_DB: mobdb
