version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "3005:3005"
      - "9229:9229"
      - "35729:35729"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mobexample
      POSTGRES_DB: mobdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
