mutation createEntity {
  createUsers(input:{
    name:"empresa5",
    password:"123456789",
    ID:"489845544",
    IDType: cc
    email:"empresa5@gmail.com",
    type:entity
    workFor:"59921ea1b136d803cba449b8"
  }) {
    errors {
      message 
      name 
      code
    }
    transactions {
      message
      status
      data {
        ok 
        id 
      }
    }
  }
}
