mutation crearArchivo($files: [Upload!]) {
	createDocuments(
    files:$files
    input:[
      {
        files: [
          {
            filename:"sanpacho2018.jpg"
            mimetype:"image/jpg"
            size: "400"
          },
          {
            filename:"yolo.pdf"
            mimetype:"application/pdf"
            size: "3000"                        
          },
          {
            filename:"mercado.png"
            mimetype:"image/png"
            size: "3000"             
          },
          {
            filename:"quibdo.jpg"
            mimetype:"image/jpg"
            size: "3000"                         
          }
        ]
        name: "foto de encuentro #2"
        departament: "5c55ee4bbafb57422ad87e48"
        city: "5c55edc4c6b06141818d9773"
        type:PHOTO
      }
    ]
  ) {
    transactions {
      message 
      status 
      data {
        departament 
        description
        city 
        type 
        id
        files {
          id 
          url 
          filename
          mimetype
        }
     } 
    }
    errors {
      message 
      name 
      code
    }
  }  
}

