subscription WATCH_UPLOAD($token:String!) {
  createDocuments(id:$token) {
    transactions {
      message 
      status 
      data {
        departament 
        description
        city 
        type 
        id
        files {
          id 
          url 
          filename
          mimetype
        }
      } 
    }
    errors {
      message 
      name 
      code
    }      
  } 
} 