mutation crearArchivo($files: [Upload!]) {
	createDocuments(
    files:$files
    input:[
      {
        files: [
          {
            filename:"champeta.mp4"
            mimetype:"video/mp4"
            size: "13000"            
          }
        ]
        name: "acta #4"
        departament: CHOCO
        city:Tado
        type:ACTA
      }
    ]
  ) {
    transactions {
      message 
      status 
      data {
        departament 
        description
        city 
        type 
        files {
          id 
          url 
          filename
          mimetype
        }
     } 
    }
    errors {
      message 
      name 
      code
    }
  }  
}

