subscription WATCH_UPLOAD($token:String!) {
  fileUpload(id:$token) {
    error {
      message 
      name
      code
    }
    data {
      id 
      url 
      filename
      mimetype
    }
  }   
} 